# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  anca_dx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  anca_dx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  anca_dx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  anca_sx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  anca_sx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  anca_sx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_dx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_dx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_dx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_sx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_sx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  femore_sx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_dx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_dx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_dx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_sx_1_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_sx_2_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  tibia_sx_3_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0