# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: dx_1
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - anca_dx_1_joint
    - femore_dx_1_joint
    - tibia_dx_1_joint
    - anca_dx_2_joint
    - femore_dx_2_joint
    - tibia_dx_2_joint
    - anca_dx_3_joint
    - femore_dx_3_joint
    - tibia_dx_3_joint
    - anca_sx_1_joint
    - femore_sx_1_joint
    - tibia_sx_1_joint
    - anca_sx_2_joint
    - femore_sx_2_joint
    - tibia_sx_2_joint
    - anca_sx_3_joint
    - femore_sx_3_joint
    - tibia_sx_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
control_dx_3:
  type: position_controllers/JointPositionController
  joints:
    - anca_dx_3_joint
    - femore_dx_3_joint
    - tibia_dx_3_joint
  gains:
    anca_dx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_dx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_dx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
control_dx_2:
  type: position_controllers/JointPositionController
  joints:
    - anca_dx_2_joint
    - femore_dx_2_joint
    - tibia_dx_2_joint
  gains:
    anca_dx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_dx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_dx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
control_sx_1:
  type: position_controllers/JointPositionController
  joints:
    - anca_sx_1_joint
    - femore_sx_1_joint
    - tibia_sx_1_joint
  gains:
    anca_sx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_sx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_sx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
control_sx_3:
  type: position_controllers/JointPositionController
  joints:
    - anca_sx_3_joint
    - femore_sx_3_joint
    - tibia_sx_3_joint
  gains:
    anca_sx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_sx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_sx_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
control_sx_2:
  type: position_controllers/JointPositionController
  joints:
    - anca_sx_2_joint
    - femore_sx_2_joint
    - tibia_sx_2_joint
  gains:
    anca_sx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_sx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_sx_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
control_dx_1:
  type: position_controllers/JointPositionController
  joints:
    - anca_dx_1_joint
    - femore_dx_1_joint
    - tibia_dx_1_joint
  gains:
    anca_dx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    femore_dx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tibia_dx_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1